In [1]:
import cv2
from ultralytics import YOLO
import traceback
import numpy as np

# Pose model
There are 17 key points in each model, but if one of the key points is not visible, the model just makes an educated guess. I believe that Will had the key points labeled correctly as the nose, eyes, ears, shoulders, elbows, wrists, hips, knees, and ankles. I chose to have my model not only plot the key points, but also output them so that we can have a better understanding of what the model is doing.

In [2]:
#creates the pose model and inputs the image
model = YOLO('yolov8m-pose.pt')
results = model('testImage.jpg')

#plots the key points on the image and creates a new image from it
frame = results[0].plot()
cv2.imshow("YOLOv8 Inference", frame)

keypoints = results[0].keypoints.xy[0]
for keypoint in keypoints : print(keypoint)

#waits until the user hits any key to close the image
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)


image 1/1 /Users/aidan/Desktop/Senior design/senior-design/core/testImage.jpg: 384x640 1 person, 720.1ms
Speed: 2.8ms preprocess, 720.1ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)


tensor([633.2852, 212.6786])
tensor([628.8334, 201.9050])
tensor([619.6083, 213.4925])
tensor([631.9985, 211.0657])
tensor([613.4843, 242.4118])
tensor([662.2421, 239.3922])
tensor([637.2760, 296.2173])
tensor([610.3989, 170.1040])
tensor([633.3550, 362.6978])
tensor([572.7612,  64.7303])
tensor([630.1616, 462.3123])
tensor([731.4772, 412.5997])
tensor([676.5093, 435.6095])
tensor([826.9346, 491.5668])
tensor([570.1587, 527.4764])
tensor([840.9533, 593.6512])
tensor([406.8344, 624.2863])


-1